/*This file is automatically generated from model configuration*/

#ifndef FREQ_CONF_H
#define FREQ_CONF_H

#define SAMPLING_FREQUENCY 24000

#define FRAME_SHIFT 240

#define WINDOW_LENGTH 660

#define FFT_LENGTH 2048

#define HPASS_FILT_TAPS 1023

#define MEL_DIM 80



#endif
